version: "3.8"
services:
        mongodb:
                image: "mongodb/mongodb-community-server:latest"
                restart: always
                networks:
                        - local-agent-network
                deploy:
                        replicas: 1
                volumes:
                        - redis:/var/lib/housing-server/mongodb/data
        # elasticsearch:
        #         image: "docker.elastic.co/elasticsearch/elasticsearch:8.7.1"
        #         container_name: elasticsearch
        #         restart: always
        #         ports:
        #           - 9200:9200
        #         networks:
        #                 - local-agent-network
        #         deploy:
        #                 replicas: 1
        #                 resources:
        #                   limits:
        #                     memory: 4GB
        #         environment:
        #                 - discovery.type=single-node
        #         volumes:
        #                 - redis:/var/lib/housing-server/elasticsearch/data
        # kibana:
        #         image: docker.elastic.co/kibana/kibana:8.7.1
        #         environment:
        #           SERVER_NAME: kibana.example.org
        #           ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        #         ports:
        #           - 5601:5601
        #         networks:
        #                 - local-agent-network
        #         deploy:
        #                 replicas: 1
        #                 resources:
        #                   limits:
        #                     memory: 1GB
        #         volumes:
        #                 - redis:/var/lib/housing-server/kibana/data
        elasticsearch:
            image: elasticsearch:8.2.2
            environment:
              - discovery.type=single-node
              - ES_JAVA_OPTS=-Xms1g -Xmx1g
              - xpack.security.enabled=false
            volumes:
              - es_data:/usr/share/elasticsearch/data
            ports:
              - target: 9200
                published: 9200
            networks:
              - elastic

        kibana:
            image: kibana:8.2.2
            ports:
              - target: 5601
                published: 5601
            depends_on:
              - elasticsearch
            networks:
              - elastic      
        redis:
                image: "redis:alpine"
                restart: always
                networks:
                        - local-agent-network
                deploy:
                        replicas: 1
                volumes:
                        - redis:/var/lib/tacobot/redis/data

networks:
        elastic:
            name: elastic
            driver: bridge
        local-agent-network:
                driver: bridge

volumes:
        mongodb:
                driver: local
        # elasticsearch:
        #         driver: local
        # kibana:
        #         driver: local
        es_data:
            driver: local
        redis:
                driver: local
