prompts = {
    "introduction": [
        "Welcome to the House Recommendation System! We have property listings from areas close to Los Angeles, California. Let's get you your dream home!",
        "Welcome to our House Recommendation System! We have a range of property listings in the vicinity of Los Angeles, California. Let's help you find your ideal home!",
        "We welcome you to our House Recommendation System! We offer a variety of property listings near Los Angeles, California. Let's work together to find your dream home!",
        "We're delighted to have you here in our House Recommendation System! Our property listings are located in close proximity to Los Angeles, California. Let's start the journey to finding your perfect home!",
        "Welcome to the House Recommendation System! We specialize in property listings near Los Angeles, California. Let's begin the search for your dream home!",
        "Welcome to our House Recommendation System! Our extensive property listings are located in areas near Los Angeles, California. Let's embark on the quest to find your ideal home!",
        "Thank you for joining us in the House Recommendation System! We have a wide selection of properties available in close proximity to Los Angeles, California. Let's work together to find your dream home!",
        "We're excited to have you here in our House Recommendation System! Our property listings cover areas near Los Angeles, California. Let's find the perfect home for you!",
        "We welcome you to the House Recommendation System! Our property listings are from areas near Los Angeles, California. Let's begin the journey of finding your dream home!",
        "Welcome to our House Recommendation System! We have an array of property listings located in proximity to Los Angeles, California. Let's work together to find your ideal home!",
        "Thank you for choosing our House Recommendation System! Our property listings cover areas near Los Angeles, California. Let's start the search for your dream home!",
        "We're thrilled to have you here in our House Recommendation System! Our property listings are situated close to Los Angeles, California. Let's find your perfect home together!",
        "We welcome you to join us in the House Recommendation System! We offer a range of property listings near Los Angeles, California. Let's begin the search for your dream home!",
        "Welcome to our House Recommendation System! Our diverse property listings are located in areas in close proximity to Los Angeles, California. Let's find your dream home together!",
        "Welcome to the House Recommendation System! We have a variety of property listings near Los Angeles, California. Let's embark on the journey of finding your ideal home!",
        "We're delighted to have you here in our House Recommendation System! Our property listings are available in areas near Los Angeles, California. Let's work together to find your dream home!"
    ],

    "lq_bedrooms": [
        "How many bedrooms are you looking for in the house?",
        "What's your ideal number of bedrooms in the house?",
        "How many bedrooms are you aiming for in the house?",
        "What's the desired bedroom count for the house?",
        "How many bedrooms are you interested in having in the house?",
        "What's the preferred number of bedrooms for you in the house?",
        "Are you searching for a specific number of bedrooms in the house?",
        "How many bedrooms are you seeking in the house?",
        "What's the target bedroom quantity for the house?",
        "Are you looking for a particular number of bedrooms in the house?",
        "How many bedrooms are you hoping to find in the house?",
        "What's the ideal bedroom count you're looking for in the house?",
        "Are you aiming for a specific number of bedrooms in the house?",
        "How many bedrooms are you planning to have in the house?",
        "What's the anticipated bedroom count in the house for you?",
        "Are you interested in a particular number of bedrooms in the house?",
        "How many bedrooms are you considering for the house?",
        "What's the preferred bedroom quantity for you in the house?",
        "Are you in search of a specific number of bedrooms in the house?",
        "How many bedrooms are you expecting to have in the house?"
    ],

    "lq_bathrooms": [
        "How many bathrooms do you want in the house?",
        "What's your desired bathroom count for the house?",
        "How many bathrooms are you looking for in the house?",
        "Are you aiming for a specific number of bathrooms in the house?",
        "What's the preferred number of bathrooms for you in the house?",
        "How many bathrooms are you hoping to have in the house?",
        "What's the ideal bathroom count you're looking for in the house?",
        "Are you searching for a particular number of bathrooms in the house?",
        "How many bathrooms are you interested in having in the house?",
        "What's the target bathroom quantity for the house?",
        "Are you looking for a specific number of bathrooms in the house?",
        "How many bathrooms are you considering for the house?",
        "What's the anticipated bathroom count in the house for you?",
        "Are you interested in a particular number of bathrooms in the house?",
        "How many bathrooms are you aiming to find in the house?",
        "Are you in search of a certain number of bathrooms in the house?",
        "How many bathrooms are you expecting to have in the house?",
        "What's your ideal bathroom number for the house?",
        "Are you hoping for a specific number of bathrooms in the house?",
        "How many bathrooms are you planning to have in the house?"
    ],

    "lq_area": [
        "How much area are you looking for in your house ? The average carpet area in this region is 3500 sq feet.",
        "What's the desired size of the house you're looking for? The typical floor space in this area averages at 3500 square feet.",
        "How much space are you aiming for in your house? On average, houses in this region have a carpet area of 3500 square feet.",
        "Are you looking for a specific area in your house? Houses in this region usually offer a carpet area measuring 3500 square feet.",
        "What's the preferred square footage for your house? In this region, houses tend to have a carpet area averaging at 3500 square feet.",
        "How much floor area are you hoping to have in your house? On average, houses in this region provide a carpet area of 3500 square feet.",
        "What's the ideal size you're looking for in your house? The typical measurement for carpet area in this area is 3500 square feet.",
        "Are you searching for a particular area in your house? The mean floor space available in this locality is 3500 square feet.",
        "How much space are you interested in having in your house? The average floor space available in this region is approximately 3500 square feet.",
        "What's the target square footage for your house? The average measurement for carpet area in this area is 3500 square feet.",
        "Are you looking for a specific size in your house? Most houses in this region have a carpet area of around 3500 square feet.",
        "How much area are you considering for your house? Houses in this locality typically offer a carpet area of 3500 square feet.",
        "What's the anticipated size you're looking for in your house? The typical carpeted area in this locality is approximately 3500 square feet.",
        "Are you interested in a particular area in your house? The mean size of the floor space in this region is 3500 square feet.",
        "How much floor space are you aiming to find in your house? The typical size of the floor space in this region is around 3500 square feet.",
        "What's the desired area for your house? In this area, the average size of the carpeted area is 3500 square feet.",
        "Are you in search of a certain size in your house? On average, the area covered by carpet in this region is 3500 square feet.",
        "How much area are you expecting to have in your house? On average, the carpeted area in this region spans 3500 square feet.",
        "What's your ideal square footage for your house? In this area, houses generally have a carpet area of 3500 square feet.",
        "Are you hoping for a specific area in your house? The mean carpet area in this locality measures 3500 square feet.",
        "How much space are you planning to have in your house? The average floor area in this area is 3500 square feet."
    ],

    "lq_price": [
        "What is your budget for home purchase? The average cost of a house in this area is roughly $3,000,000. House prices start at about $700k, and could go all the way up to $17M, depending on the amenities."
        "How much are you willing to spend on buying a home? On average, houses in this area are priced at approximately $3,000,000. The starting price for houses is around $700,000, but it can go up to $17 million, depending on the amenities.",
        "What is the allocated budget for purchasing a home? The mean price of a house in this region is approximately $3,000,000. House prices commence at about $700,000 and can go as high as $17 million, depending on the amenities.",
        "What is the financial limit for your home purchase? The average price of a house in this locality is approximately $3,000,000. House prices start at around $700,000 and can go up to $17 million, depending on the amenities.",
        "What is the amount you have set aside for buying a home? The mean price of a house in this locality is around $3,000,000. House prices start at about $700,000 and can go as high as $17 million, depending on the amenities.",
        "How much money are you planning to spend on a home purchase? On average, houses in this area are priced at approximately $3,000,000. The starting price for houses is approximately $700,000, but it can go up to $17 million, depending on the amenities.",
        "What is the maximum budget you have for buying a home? On average, houses in this area are valued at roughly $3,000,000. House prices can start from approximately $700,000 and escalate to $17 million, depending on the amenities.",
        "How much are you looking to invest in a home purchase? Houses in this region typically have a cost of about $3,000,000. The price range for houses starts at approximately $700,000 and can extend up to $17 million, depending on the amenities.",
        "What is the price range you are considering for buying a home? The average price of a house in this locality is around $3,000,000. House prices begin at about $700,000 and can climb up to $17 million, depending on the amenities.",
        "What is the budget you have in mind for purchasing a home? On average, houses in this area are priced at approximately $3,000,000. The starting price for houses is about $700,000, but it can go up to $17 million, depending on the amenities.",
        "How much are you prepared to pay for a home purchase? The typical price of a house in this locality is roughly $3,000,000. House prices begin at approximately $700,000 and can reach as high as $17 million, depending on the amenities.",
        "What is the upper limit of your budget for buying a home? Houses in this area have an average cost of about $3,000,000. The price range for houses begins at approximately $700,000 and can reach up to $17 million, depending on the amenities.",
        "How much money do you have available for a home purchase? The average cost of a house in this region is approximately $3,000,000. House prices can start from around $700,000 and go up to $17 million, depending on the amenities.",
        "What is the maximum amount you are comfortable spending on a home? Houses in this region typically have a cost of approximately $3,000,000. The price range for houses starts at about $700,000 and can extend up to $17 million, depending on the amenities.",
        "How much have you budgeted for the purchase of a home? The average price of a house in this locality is approximately $3,000,000. House prices start at around $700,000 and can go up to $17 million, depending on the amenities.",
        "What is the price bracket you have in mind for a home purchase? The typical cost of a house in this area is roughly $3,000,000. House prices can range from approximately $700,000 to $17 million, depending on the amenities.",
        "What is the total amount you are planning to invest in a home? Houses in this area have an average cost of around $3,000,000. The price range for houses starts at about $700,000 and can go up to $17 million, based on the amenities.",
        "How much are you aiming to allocate for a home purchase? On average, houses in this area are valued at roughly $3,000,000. House prices can begin from approximately $700,000 and go as high as $17 million, depending on the amenities.",
        "What is the budgetary constraint for your home purchase? Houses in this region typically have a cost of approximately $3,000,000. The price range for houses starts at about $700,000 and can extend up to $17 million, depending on the amenities.",
        "How much money have you earmarked for buying a home? The mean price of a house in this locality is around $3,000,000"
    ],

    "lq_house_flooring": [
        "What type of house flooring do you prefer from among vinyl, linoleum, hardwood? Vinyl flooring comes at a premium of about $14 per square foot, hardwood flooring at about $30 per square foot.",
        "Among vinyl, linoleum, and hardwood flooring options, which type do you prefer for your house? For each square foot, vinyl flooring is priced at around $14, while hardwood flooring costs approximately $30.",
        "Do you have a preference for the type of flooring between vinyl, linoleum, and hardwood for your house? Vinyl flooring is priced at approximately $14 per square foot, while hardwood flooring costs around $30 per square foot.",
        "Which flooring material would you like to have in your house: vinyl, linoleum, or hardwood? Vinyl flooring is available at a premium of about $14 for each square foot, while hardwood flooring costs around $30 per square foot.",
        "From vinyl, linoleum, and hardwood flooring, which one do you favor for your house? Vinyl flooring is available at a premium of about $14 for each square foot, while hardwood flooring costs around $30 per square foot.",
        "Are you inclined towards vinyl, linoleum, or hardwood flooring for your house? The premium for vinyl flooring is approximately $14 per square foot, while hardwood flooring costs around $30 per square foot.",
        "Among vinyl, linoleum, and hardwood, which flooring option suits your preference for your house? The price per square foot for vinyl flooring is approximately $14, while hardwood flooring comes at about $30.",
        "Which type of house flooring do you lean towards: vinyl, linoleum, or hardwood? The cost of vinyl flooring per square foot is approximately $14, while hardwood flooring is priced at about $30 per square foot.",
        "Do you have a specific choice for the house flooring between vinyl, linoleum, and hardwood? Vinyl flooring has a price tag of about $14 per square foot, while hardwood flooring is priced at approximately $30 per square foot.",
        "Among vinyl, linoleum, and hardwood flooring options, which one do you lean towards for your house? Vinyl flooring is available at a premium of around $14 per square foot, while hardwood flooring comes at approximately $30 per square foot.",
        "Do you have a preferred flooring type in mind for your house: vinyl, linoleum, or hardwood? Vinyl flooring comes at a premium of approximately $14 per square foot, while hardwood flooring is priced at about $30 per square foot.",
        "Which flooring material do you prefer for your house: vinyl, linoleum, or hardwood? For vinyl flooring, the price per square foot is approximately $14, whereas hardwood flooring is priced at about $30 per square foot.",
        "From vinyl, linoleum, and hardwood flooring options, which one is your preference for your house? Vinyl flooring is priced at approximately $14 for every square foot, whereas hardwood flooring costs around $30 per square foot.",
        "Are you more inclined towards vinyl, linoleum, or hardwood flooring for your house? The cost of vinyl flooring is about $14 per square foot, whereas hardwood flooring is priced at approximately $30 per square foot.",
        "Do you have a specific preference for the type of flooring in your house: vinyl, linoleum, or hardwood? The premium for vinyl flooring is about $14 per square foot, while hardwood flooring is priced at approximately $30 per square foot.",
        "Among vinyl, linoleum, and hardwood, which type of flooring do you favor for your house? For each square foot, vinyl flooring is priced at around $14, whereas hardwood flooring costs approximately $30.",
        "Which flooring option appeals to you the most for your house: vinyl, linoleum, or hardwood? The price per square foot for vinyl flooring is about $14, whereas hardwood flooring is priced at around $30 per square foot.",
        "Do you lean towards vinyl, linoleum, or hardwood flooring for your house? The price per square foot for vinyl flooring is approximately $14, while hardwood flooring comes at about $30.",
        "Are you partial towards vinyl, linoleum, or hardwood flooring for your house? Vinyl flooring has a price tag of around $14 per square foot, whereas hardwood flooring costs approximately $30 per square foot.",
        "Among vinyl, linoleum, and hardwood flooring, which one would you choose for your house? The cost of vinyl flooring per square foot is approximately $14, whereas hardwood flooring is priced at around $30 per square foot.",
        "Do you have a specific inclination towards the type of flooring in your house: vinyl, linoleum, or hardwood?, Vinyl flooring comes at a premium of approximately $14 per square foot, while hardwood flooring is priced at about $30 per square foot."
    ],

    "lq_house_age": [
        "What is the approximate age of the house you are interested in?",
        "Can you provide an estimate of the house's age that you're looking at?",
        "What is your guess about the age of the house you are considering?",
        "Do you have an idea about how old the property you're interested in is?",
        "Could you estimate how many years old the home you're interested in is?",
        "How old would you say the house you're eyeing is?",
        "Do you know the rough age of the home you're looking into?",
        "What's the possible age of the property you're contemplating?",
        "What might be the age range of the house that's caught your interest?",
        "Are you aware of how old the house you're thinking about purchasing is?",
        "Can you approximate the age of the house you're interested in was erected?",
        "Have you got an idea of the age of the residence you're considering?"
    ],

    "lq_sea_proximity": [
        "What is your desired proximity to the seaside for a house? We have houses by the seaside, <1 Hour commute to the sea and houses further inland.",
        "How close would you like to be to the ocean when choosing a house? We offer options right by the shore, within a less than one-hour commute, and farther inland.",
        "What level of closeness to the seaside would you prefer when selecting a house? Our properties include those directly by the shore, within an hour's travel time to the sea, and properties located further inland.",
        "Regarding your ideal distance from the coastline, what are your preferences for a house? We have houses available right by the seaside, within an hour's commute to the sea, and properties located further inland.",
        "How near to the seaside would you like your house to be? Our options include properties by the shore, within a one-hour commute to the sea, and houses located farther inland.",
        "What proximity to the seaside are you looking for in a house? We offer houses directly by the shore, within a <1 Hour commute to the sea, as well as properties situated further inland.",
        "When it comes to the seaside, how close would you like your house to be? We provide houses by the shore, within an hour's travel to the sea, and properties farther inland.",
        "What is your preferred distance from the seaside when selecting a house? We have options available right by the seaside, within a one-hour commute to the sea, and houses located further inland.",
        "How far would you like your house to be from the ocean? We have houses by the shore, within a <1 Hour commute to the sea, and properties further inland.",
        "What level of proximity to the seaside would you like your house to have? We offer properties by the shore, within an hour's travel time to the sea, and houses located farther inland.",
        "What distance from the seaside are you aiming for when choosing a house? Our available properties include houses by the shore, within a one-hour commute to the sea, and properties situated further inland."
    ],

    "lq_school_rating": [
        "We offer localiion-vise rating in terms of the school district going from 1 to 5 star. 5 star school district homes are generally premium, with neighborhoods especially designed in a children-friendly manner. What school district rating are you interested in?",
        "We provide a rating system based on the location, specifically the school district, ranging from 1 to 5 stars. Homes in 5-star school districts are typically considered high-end, with neighborhoods specifically designed to be child-friendly. What rating are you looking for in a school district?",
        "Our rating system takes into account the school district when it comes to location, ranging from 1 to 5 stars. Homes in 5-star school districts are typically of premium quality, with neighborhoods specifically designed to cater to children's needs. What rating are you seeking for the school district?",
        "We offer a location-based rating system that assesses the school district, ranging from 1 to 5 stars. Homes situated in 5-star school districts are generally considered top-tier, featuring neighborhoods specifically designed to be child-friendly. What rating would you prefer for the school district?",
        "In terms of location, we provide a rating system based on the quality of the school district, ranging from 1 to 5 stars. Homes located in 5-star school districts are typically luxurious, with neighborhoods specially designed to accommodate families with children. What rating are you interested in for the school district?",
        "We have a location-specific rating system that takes into consideration the quality of the school district, rated from 1 to 5 stars. Homes in 5-star school districts are generally high-end, with neighborhoods designed to be child-friendly. What rating are you looking for in terms of the school district?",
        "When it comes to location, we offer a rating system based on the school district, ranging from 1 to 5 stars. Homes in 5-star school districts are typically considered upscale, with neighborhoods specially designed to provide a child-friendly environment. What school district rating are you interested in?",
        "Our location-vise rating system includes an assessment of the school district, ranging from 1 to 5 stars. Homes located in 5-star school districts are usually premium properties, featuring neighborhoods specifically designed with children in mind. What rating for the school district are you considering?",
        "We provide a rating system that evaluates the school district based on location, with ratings ranging from 1 to 5 stars. Homes situated in 5-star school districts are generally high-end, featuring neighborhoods designed to be particularly friendly for children. What rating are you looking for in terms of the school district?",
        "Our rating system takes location into account, specifically the school district, and rates it from 1 to 5 stars. Homes in 5-star school districts are typically considered top-tier, with neighborhoods designed to be especially welcoming for children. What rating would you prefer for the school district?",
        "We offer a location-based rating system that assesses the quality of the school district on a scale of 1 to 5 stars. Homes in 5-star school districts are generally considered prestigious, with neighborhoods designed to be child-friendly. What rating are you seeking for the school district?",
        "When it comes to location, we have a rating system that considers the school district, ranging from 1 to 5 stars. Homes in 5-star school districts are typically of high value, with neighborhoods specially designed to cater to the needs of children. What rating are you interested in for the school district?",
        "Our rating system takes into account the school district's quality in terms of location, with ratings ranging from 1 to 5 stars. Homes in 5-star school districts are generally premium properties, featuring neighborhoods specifically designed to create a child-friendly atmosphere. What school district rating are you looking for?",
        "We provide a location-based rating system that evaluates the school district, ranging from 1 to 5 stars. Homes located in 5-star school districts are typically considered upscale, with neighborhoods designed to cater to the needs of families with children. What rating are you interested in for the school district?"
    ],

    "lq_house_public_transport": [
        "Houses could have one of the 2 public transport options : Bus Stop or Subway. Homes with close access to the subway are generally a bit costlier. Which one do you prefer ?",
        "Houses offer a choice between two public transportation options: a bus stop or a subway. Homes with convenient access to the subway usually have a slightly higher price tag. Which option would you prefer?",
        "Homes can be connected to either a bus stop or a subway for public transportation. Generally, houses with easy access to the subway tend to be slightly more expensive. Which option are you inclined towards?",
        "Houses come with the availability of either a bus stop or a subway for public transportation. Properties with close proximity to the subway typically have a slightly higher cost. Which option would you like to prioritize?",
        "There are two public transport options available for houses: a bus stop or a subway. Homes located near the subway are generally priced a bit higher. Which option is your preference?",
        "When it comes to houses, you have a choice between a bus stop or a subway for public transportation. Homes near the subway are usually priced a little higher. Which option are you leaning towards?",
        "Houses offer the convenience of either a bus stop or a subway for public transportation. Properties with nearby subway access often come with a slightly higher price. Which option do you prefer?",
        "You have the option of either a bus stop or a subway for public transportation when choosing a house. Typically, homes with close proximity to the subway are priced slightly higher. Which option would you like to go for?"
    ],

    "lq_neighborhood_features": [
        "Any other neighborhood features you would like. These could include Gyms, Cafes, Diners, Movie theaters, Parks, Activity Centers, Saunas and so forth. You can get creative here but remember these features come with a price bump!",
        "Are there any additional amenities or features you would like in the neighborhood? This could encompass gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and more. However, please keep in mind that these features may result in an increase in price.",
        "Would you like any other neighborhood perks or facilities? These could consist of gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and other options. Just remember that these features may come with an additional cost.",
        "Are there any specific neighborhood amenities you desire? This could include gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and various other possibilities. However, please note that these features may come at an elevated price.",
        "Do you have any preferences for other neighborhood attributes? This could involve gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and more. It's important to bear in mind that opting for these features may result in a higher price point.",
        "Are there any other neighborhood characteristics you are interested in? This may encompass gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and other options. Keep in mind that these features may come with an additional cost.",
        "Would you like any additional neighborhood amenities? This might include gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and more. However, please be aware that selecting these features may lead to an increase in price.",
        "Are there any other specific neighborhood features you would like to have? This could consist of gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and various other possibilities. Just keep in mind that these amenities may come with a higher price tag.",
        "Do you have any preferences for other amenities in the neighborhood? This could include gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and more. However, please note that these features may result in an increase in price.",
        "Are there any additional neighborhood elements you would like to consider? This might involve gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and various other options. Just remember that these features may come at a higher cost.",
        "Would you like any other neighborhood perks or facilities to be included? This could consist of gyms, cafes, diners, movie theaters, parks, swimming pools, activity centers, saunas, and more. Please keep in mind that selecting these features may lead to a price increase."
    ],

    "invalid_response": [
        "Sorry! I didn't get that. Let's try again.",
        "Apologies, I didn't understand. Can you please provide a clearer response?",
        "I'm sorry, but I didn't grasp your previous answer. Could you kindly try explaining it again?",
        "My apologies for the confusion. Can you please rephrase your answer for me?",
        "I didn't quite catch what you said. Could you please repeat your response?",
        "Sorry, I didn't comprehend your answer. Can you please try restating it?",
        "I apologize for the misunderstanding. Could you please provide a different answer?",
        "I'm afraid I didn't follow your response. Can you try answering that once more?",
        "Sorry for the confusion. Could you please try giving your answer again?",
        "I didn't get the answer clearly. Can you please try responding once more?",
        "Apologies, I couldn't understand your previous answer. Could you try rephrasing it?",
        "Sorry for the mix-up. Can you please provide a revised answer?",
        "I'm sorry, I didn't catch that. Could you please repeat your response?",
        "My apologies for not understanding. Can you please try answering again?",
        "Sorry, I didn't grasp your answer. Can you please try explaining it differently?",
        "I didn't quite get what you said. Could you please repeat your answer for me?",
        "Sorry, I didn't comprehend your response. Can you please try restating it?",
        "I apologize for the confusion. Could you please provide a different answer?",
        "I'm afraid I didn't follow your answer. Can you try answering that once more?",
        "Sorry for the misunderstanding. Could you please try giving your answer again?",
        "I didn't get the answer clearly. Can you please try responding once more?"
    ]
}
